### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-11#36]
*Congratulations on finishing milestone 2! We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### Code is abstracted to functions with good function design

- [ ] There are cases of functions that do not check for proper input and/or do not provide useful error messages. **- 1**

`correlation_graph`

- [ ] Functions do not follow a consistent style. **-1**

### Functions are well documented

- [ ] The example in `correlation_graph` is clearly incorrect. **- 1**

### Tests are written for each function, and work expected

- I got an error while trying to run the tests. **- 3**

```
✔ | F W S  OK | Context
✖ | 1       0 | testthat
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error (testthat.R:2:1): (code run outside of `test_that()`)
Error in `library(DSCI - 310 - Group - 11)`: 'package' must be of length 1
Backtrace:
 1. base::library(DSCI - 310 - Group - 11) testthat.R:2:0
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

══ Results ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
[ FAIL 1 | WARN 0 | SKIP 0 | PASS 0 ]
Error: Test failures
In addition: Warning message:
package ‘testthat’ was built under R version 4.1.2
```

### Tests suite is of high quality

- [ ] There are cases of functions that do not test at least 1 edge-case input. **- 2**

`data_cleaning`, `recipe_scale_center`

- [ ] There are cases of functions that do not test at least 2 expected input. **- 0.5**

`data_cleaning`

### GitHub Issue Milestones

- [ ] GitHub issue milestones were not used. **- 2**

###  Analysis can be run reproducibly using documentation provided in the README

- [ ] Clearly specify usage instructions to the point a user could copy and paste them and they would work.
If a specific value needs to be inserted (e.g., volume mounting, port forwarding, tag version - which should be specified, as relying on `latest` is unreliable for many reasons, etc)
suggest the most reasonable value and provide the list
(or link to a list) of alternative options. **-2**

You should give the command for cloning and navigating.

- [ ] I could not reproduce the analysis because there is no repository available inside the container. The docker command is probably missing a volume argument. **- 3**

- [ ] Could not reproducibly run the analysis because a package was missing from the provided computational environment. **-5**

```
Error: Some package installs are required: 'kknn', 'kknn'
Traceback:

1. fire_wkflw %>% tune_grid(resamples = fire_cv, grid = gridvals) %>%
 .     collect_metrics() %>% filter(.metric == "rmse")
2. filter(., .metric == "rmse")
3. collect_metrics(.)
4. tune_grid(., resamples = fire_cv, grid = gridvals)
5. tune_grid.workflow(., resamples = fire_cv, grid = gridvals)
6. tune_grid_workflow(object, resamples = resamples, grid = grid,
 .     metrics = metrics, pset = param_info, control = control)
7. check_workflow(workflow, pset = pset)
8. check_installs(mod)
9. stop("Some package installs are required: ", paste0("'", deps[!is_inst],
 .     "'", collapse = ", "), call. = FALSE)
 ```

**Comment by a-kong** [comment]
Hi @GiuseppeTT, we got docked marks for not using GitHub issue milestones, but we did. [Here](https://github.com/DSCI-310/DSCI-310-Group-11/milestone/2) is the link showing that we used it.
