### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-11#50]
*Congratulations on finishing milestone 2! We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### Code is abstracted to functions with good function design

- [x] DSCI-310/DSCI-310-Group-11-package#11

`correlation_graph`

- [x] Functions do not follow a consistent style. **-1**

### Functions are well documented

- [x] #70

### Tests are written for each function, and work expected

- I got an error while trying to run the tests. **- 3**

```
✔ | F W S  OK | Context
✖ | 1       0 | testthat
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error (testthat.R:2:1): (code run outside of `test_that()`)
Error in `library(DSCI - 310 - Group - 11)`: 'package' must be of length 1
Backtrace:
 1. base::library(DSCI - 310 - Group - 11) testthat.R:2:0
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

══ Results ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
[ FAIL 1 | WARN 0 | SKIP 0 | PASS 0 ]
Error: Test failures
In addition: Warning message:
package ‘testthat’ was built under R version 4.1.2
```

### Tests suite is of high quality

- [x] DSCI-310/DSCI-310-Group-11-package#8

`data_cleaning`, `recipe_scale_center`

- [x] DSCI-310/DSCI-310-Group-11-package#7

`data_cleaning`

### GitHub Issue Milestones

- [x] GitHub issue milestones were not used. **- 2**

###  Analysis can be run reproducibly using documentation provided in the README

- [x] #56
If a specific value needs to be inserted (e.g., volume mounting, port forwarding, tag version - which should be specified, as relying on `latest` is unreliable for many reasons, etc)
suggest the most reasonable value and provide the list
(or link to a list) of alternative options. **-2**

You should give the command for cloning and navigating.

- [x] #59

- [x] #64

```
Error: Some package installs are required: 'kknn', 'kknn'
Traceback:

1. fire_wkflw %>% tune_grid(resamples = fire_cv, grid = gridvals) %>%
 .     collect_metrics() %>% filter(.metric == "rmse")
2. filter(., .metric == "rmse")
3. collect_metrics(.)
4. tune_grid(., resamples = fire_cv, grid = gridvals)
5. tune_grid.workflow(., resamples = fire_cv, grid = gridvals)
6. tune_grid_workflow(object, resamples = resamples, grid = grid,
 .     metrics = metrics, pset = param_info, control = control)
7. check_workflow(workflow, pset = pset)
8. check_installs(mod)
9. stop("Some package installs are required: ", paste0("'", deps[!is_inst],
 .     "'", collapse = ", "), call. = FALSE)
 ```

**Comment by GiuseppeTT** [comment]
@a-kong Could you send a message to me on Canvas about the milestone issue? I know that I regraded one group, not sure if it is your group
