### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-11#72]
*Congratulations on finishing milestone 2! We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### Analysis code is abstracted to four (or more) scripts which take command line arguments and save analysis artifacts (e.g., figures and data for tables).

- [ ] One or more scripts are not well documented **- 4**

Scripts are missing argument documentation.

### Report is written in a literate code document, and the code in the literate code document primarily functions to source analysis artifacts and format the document.

- [ ] The literate code document (R Markdown or Jupyter notebook) does not use code to automatically update inline values generated from the analysis that are presented in the narrated text of the document but it does not work correctly or a few missing cases. **- 2**

"with a majority of the points concentrated around `ISI` values of -1.25 to 1.25."

### Project file and directory structure organization

- [ ] There are folder/files that should not be committed. **- 1**

The legacy analysis file `data_analysis.ipynb` is still in the `reports/` folder.

###  Analysis can be run reproducibly using documentation provided in the README

- [ ] Usage documentation could be improved for clarity (i.e., it is not explicitly clear to the user how to use the project, or some of the wording is confusing). **-2**

Instructions on how and where to access the analysis are missing.
